abstract: create and validate Captcha for Sledge.
author: Tokuhiro Matsuno  C<< <tokuhiro __at__ mobilefactory.jp> >>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Sledge-Plugin-Captcha
no_index: 
  directory: 
    - inc
    - t
requires: 
  GD::SecurityImage: 0
  Sledge::Plugin::ShowImage: 0
version: 0.01
